### PR TITLE
TLS 1.3 addition for Win10 v1903 and Server 2019 v1903

### PR DESCRIPTION
**Pull request by PedroAsani**

### CODE REVIEW

**Review by JonathanPitre — APPROVED** [review]

**Comment by JonathanPitre** [comment]
Hi @Crosse, can you please approve this pull request ? It looks fine to me.

**Comment by Crosse** [comment]
Sheesh, yes. Sorry about that. One moment...

**Comment by JonathanPitre** [comment]
@Crosse for TLS 1.3, this needs to be fixed from

SUPPORTED_Windows_10_0 (line 392)
to
SUPPORTED_Windows_10_0_RS6_NOSERVER

so it's only enable on Windows 10 1903. There's no such thing as Windows Server 2019 1903 (with GUI at least)

**Comment by Crosse** [comment]
@JonathanPitre I don't have a Windows environment any longer to test these PRs, so I rely on those who submit pull requests to test their changes before creating the PR. @PedroAsani has done good work in the past, and because I can't test these changes, the best I can do is usually just verify the XML and other basic checks. I'll make this change, but if there are other issues with this PR, I'll have to leave it up to you (or others!) to submit a PR to fix them.

(I'll also make the disclaimer on the README a little more prominent.)

**Pull request merged**
